# Checks if the current updates includes incompatible changes compared with latest release.

name: Detect incompatible changes

on:
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
    branches:
      - 'main'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: './grafana-plugin-sdk-go'
    - uses: actions/setup-go@v5
      with:
        cache: false
        check-latest: true
        go-version-file: './grafana-plugin-sdk-go/go.mod'

    - name: Install gorelease
      working-directory: './grafana-plugin-sdk-go'
      run: go install golang.org/x/exp/cmd/gorelease@latest

    - name: Check for incompatible changes
      working-directory: './grafana-plugin-sdk-go'
      run: |
        gorelease | tee /dev/stderr | grep -vzq 'incompatible changes'
