name: Run Tests

on:
  pull_request:
    branches:
      - v1-maint
  push:
    branches:
      - v1-maint
    tags:
      - v1.*

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.19.x, 1.20.x]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install markdown-toc

      - name: Run Tests
        run: |
          go run build.go vet
          go run build.go test
          go run build.go -tags urfave_cli_no_docs test
          go run build.go toc docs/v1/manual.md
