name: ci
on:
  push:
    branches:
      - "v4"
  pull_request:
    branches:
      - "v4"
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.15", "1.16", "1.17"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: test
        run: |
          go test ./... -v
          go test ./... -v -race
          go test ./... -v -tags noasm
          go test ./... -v -race -tags noasm
