name: Test Go
on: [push, pull_request]
jobs:
  lint-test-build:
    name: Lint, Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.15", "1.16", "1.17", "1.18"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Install Dependencies
        env:
          GOPROXY: https://proxy.golang.org,direct
        run: go mod download

      - name: Test
        run: go test -race ./...
