{
 "title": "Aggregated macros visualizations",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "$rateColumnsAggregated",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/386",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rateColumnsAggregated(datacenter, concat(datacenter,interface) AS dc_interface, sum, tx_bytes, sum, rx_bytes) FROM traffic",
     "rawQuery": "/* grafana dashboard=Aggregated macros visualizations, user=0 */ SELECT (intDiv(toUInt32(event_time), 15) * 15) * 1000 as t, count() FROM default.traffic WHERE event_date >= toDate(1714127138) AND event_date <= toDate(1714148738) AND event_time >= toDateTime(1714127138) AND event_time <= toDateTime(1714148738) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "traffic"
    }
   ]
  },
  {
   "title": "$perSeocndColumnsAggregated",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/386",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecondColumnsAggregated(datacenter, concat(datacenter,interface) AS dc_interface, sum, tx_bytes, sum, rx_bytes) FROM traffic",
     "rawQuery": "/* grafana dashboard=Aggregated macros visualizations, user=0 */ SELECT t, datacenter, sum(tx_bytesRate) AS tx_bytesRateAgg, sum(rx_bytesRate) AS rx_bytesRateAgg FROM (  SELECT t, datacenter, dc_interface, tx_bytes / runningDifference(t / 1000) AS tx_bytesRate, rx_bytes / runningDifference(t / 1000) AS rx_bytesRate  FROM (   SELECT (intDiv(toUInt32(event_time), 30) * 30) * 1000 AS t, datacenter, concat(datacenter, interface) AS dc_interface, max(tx_bytes) AS tx_bytes, max(rx_bytes) AS rx_bytes   FROM traffic WHERE event_date >= toDate(1714275253) AND event_date <= toDate(1714296853) AND event_time >= toDateTime(1714275253) AND event_time <= toDateTime(1714296853)   GROUP BY t, datacenter, dc_interface    ORDER BY t, datacenter, dc_interface  ) ) GROUP BY t, datacenter ORDER BY datacenter, t",
     "round": "0s",
     "table": "traffic"
    }
   ]
  },
  {
   "title": "$increaseColumnsAggregated",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/386",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increaseColumnsAggregated(datacenter, concat(datacenter,interface) AS dc_interface, sum, tx_bytes, sum, rx_bytes) FROM traffic",
     "rawQuery": "/* grafana dashboard=Aggregated macros visualizations, user=0 */ SELECT t, datacenter, sum(tx_bytesPerSecond) AS tx_bytesPerSecondAgg, sum(rx_bytesPerSecond) AS rx_bytesPerSecondAgg FROM (  SELECT t, datacenter, dc_interface, if(runningDifference(tx_bytes) < 0 OR neighbor(dc_interface,-1,dc_interface) != dc_interface, nan, runningDifference(tx_bytes) / runningDifference(t / 1000)) AS tx_bytesPerSecond, if(runningDifference(rx_bytes) < 0 OR neighbor(dc_interface,-1,dc_interface) != dc_interface, nan, runningDifference(rx_bytes) / runningDifference(t / 1000)) AS rx_bytesPerSecond  FROM (   SELECT (intDiv(toUInt32(event_time), 20) * 20) * 1000 AS t, datacenter, concat(datacenter, interface) AS dc_interface, max(tx_bytes) AS tx_bytes, max(rx_bytes) AS rx_bytes   FROM traffic WHERE event_date >= toDate(1714300736) AND event_date <= toDate(1714322336) AND event_time >= toDateTime(1714300736) AND event_time <= toDateTime(1714322336)   GROUP BY datacenter, dc_interface, t    ORDER BY datacenter, dc_interface, t  ) ) GROUP BY datacenter, t ORDER BY datacenter, t",
     "round": "0s",
     "table": "traffic"
    }
   ]
  },
  {
   "title": "$deltaColumnsAggregated",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/386",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$deltaColumnsAggregated(datacenter, concat(datacenter,interface) AS dc_interface, sum, tx_bytes, sum, rx_bytes) FROM traffic",
     "rawQuery": "/* grafana dashboard=Aggregated macros visualizations, user=0 */ SELECT t, datacenter, sum(tx_bytesIncrease) AS tx_bytesIncreaseAgg, sum(rx_bytesIncrease) AS rx_bytesIncreaseAgg FROM (  SELECT t, datacenter, dc_interface, if(runningDifference(tx_bytes) < 0 OR neighbor(dc_interface,-1,dc_interface) != dc_interface, nan, runningDifference(tx_bytes) / 1) AS tx_bytesIncrease, if(runningDifference(rx_bytes) < 0 OR neighbor(dc_interface,-1,dc_interface) != dc_interface, nan, runningDifference(rx_bytes) / 1) AS rx_bytesIncrease  FROM (   SELECT (intDiv(toUInt32(event_time), 30) * 30) * 1000 AS t, datacenter, concat(datacenter, interface) AS dc_interface, max(tx_bytes) AS tx_bytes, max(rx_bytes) AS rx_bytes   FROM traffic WHERE event_date >= toDate(1714305061) AND event_date <= toDate(1714326661) AND event_time >= toDateTime(1714305061) AND event_time <= toDateTime(1714326661)   GROUP BY datacenter, dc_interface, t    ORDER BY datacenter, dc_interface, t  ) ) GROUP BY datacenter, t ORDER BY datacenter, t",
     "round": "0s",
     "table": "traffic"
    }
   ]
  }
 ]
}