{
 "title": "ClickHouse Queries Analysis",
 "tags": [
  "Altinity",
  "clickhouse",
  "queries",
  "performance"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Cluster",
    "query": "vertamedia-clickhouse-datasource"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "SELECT hostName() FROM clusterAllReplicas('{cluster}', system.one)\nSETTINGS skip_unavailable_shards=1"
   },
   {
    "name": "query_kind",
    "label": "Kind",
    "query": "SELECT query_kind\nFROM clusterAllReplicas('{cluster}',merge(system,'^query_log'))\nWHERE\nevent_date BETWEEN toDate($__from / 1000) AND toDate($__to / 1000)\nAND event_time BETWEEN toDateTime($__from / 1000) AND  toDateTime($__to / 1000)\n    AND type!=1\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY query_kind \nORDER BY count() DESC\nSETTINGS skip_unavailable_shards=1"
   },
   {
    "name": "user",
    "label": "User",
    "query": "SELECT initial_user\nFROM clusterAllReplicas('{cluster}',merge(system,'^query_log'))\nWHERE\n event_date BETWEEN toDate($__from / 1000) AND toDate($__to / 1000)\n AND event_time BETWEEN toDateTime($__from / 1000) AND  toDateTime($__to / 1000)\n AND type <> 1\n $conditionalTest(AND hostName() in ($hostname),$hostname)\n $conditionalTest(AND query_kind in ($query_kind),$query_kind)\nGROUP BY initial_user\nORDER BY count() DESC\nSETTINGS skip_unavailable_shards=1"
   },
   {
    "name": "exception_code",
    "label": "Exception",
    "query": "SELECT\n   toString(exception_code) || '__' || errorCodeToName(exception_code) \nFROM clusterAllReplicas('{cluster}', merge(system,'^query_log'))\nWHERE \n   event_date BETWEEN toDate($__from / 1000) AND toDate($__to / 1000)\n   AND event_time BETWEEN toDateTime($__from / 1000) AND  toDateTime($__to / 1000)\n   AND type != 1\n   $conditionalTest(AND hostName() in ($hostname),$hostname)\n   $conditionalTest(AND query_kind in ($query_kind),$query_kind)\n   $conditionalTest(AND (initial_user in ($user) OR user in ($user)),$user)\nGROUP BY exception_code\nORDER BY count() DESC LIMIT 100\nSETTINGS skip_unavailable_shards=1"
   },
   {
    "name": "query_hash",
    "query": "SELECT\n    normalized_query_hash\nFROM clusterAllReplicas('{cluster}', merge(system,'^query_log'))\nWHERE \n   event_date BETWEEN toDate($__from / 1000) AND toDate($__to / 1000)\n   AND event_time BETWEEN toDateTime($__from / 1000) AND  toDateTime($__to / 1000)\n   AND type != 1\n   $conditionalTest(AND hostName() in ($hostname),$hostname)\n   $conditionalTest(AND query_kind in ($query_kind),$query_kind)\n   $conditionalTest(AND exception_code in ($exception_code),$exception_code)\n   $conditionalTest(AND (initial_user in ($user) OR user in ($user)),$user)\nGROUP BY normalized_query_hash\nORDER BY ${metric:raw} DESC LIMIT 80\nSETTINGS skip_unavailable_shards=1"
   },
   {
    "name": "metric",
    "query": "count : count(), query_time : sum(query_duration_ms), cpu_time : sum(ProfileEvents['OSCPUVirtualTimeMicroseconds']), read_bytes : sum(read_bytes), network_receive :  sum(ProfileEvents['NetworkReceiveBytes']), network_send : sum(ProfileEvents['NetworkSendElapsedMicroseconds']), selected_ranges : sum(ProfileEvents['SelectedRanges']), memory : quantile(0.97)(memory_usage), threads : max(peak_threads_usage), open_files : sum(ProfileEvents['FileOpen']), external_processing_files : sum(ProfileEvents['ExternalProcessingFilesTotal'])"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Queries",
   "type": "timeseries",
   "description": "CurrentMetric_Query from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT \n    $timeSeries as t,\n    hostName() as host,\n    max(CurrentMetric_Query) as QueriesRunning\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE \n$timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  { "title": "By query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Queries timeline",
   "type": "status-history",
   "description": "Every row represents queries which have the same normalized_query_hash, the higher metric is - the more red the rows is.",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "with \n   (intDiv(toUInt32(event_time), $interval)) as query_finish,\n   (intDiv(toUInt32(query_start_time), $interval)) as query_start,\n   arrayMap( i -> ( query_start + i ) * $interval * 1000, range(query_finish - query_start + 1) ) as timestamps\nSELECT \n    arrayJoin(timestamps) as t,\n    normalized_query_hash,\n    ${metric:raw} as m\nFROM merge(system,'^query_log')\nWHERE \n    event_date BETWEEN toDate($__from / 1000) - INTERVAL 1 DAY AND toDate($__to / 1000) + INTERVAL 1 DAY\n    AND event_time BETWEEN toDateTime($__from / 1000) - INTERVAL 20 MINUTE AND  toDateTime($__to / 1000) + INTERVAL 20 MINUTE\n    AND type!=1\n    $conditionalTest(AND hostName() in ($hostname),$hostname)\n    $conditionalTest(AND query_kind in ($query_kind),$query_kind)\n    $conditionalTest(AND exception_code in ($exception_code),$exception_code)\n    $conditionalTest(AND initial_user in ($user),$user)\n    AND normalized_query_hash in [$query_hash]\n    AND t BETWEEN $__from  AND $__to\nGROUP BY normalized_query_hash, t\nORDER BY count(t) OVER(PARTITION BY normalized_query_hash) DESC, sum(m) OVER(PARTITION BY normalized_query_hash) DESC\nLIMIT 200 BY t",
     "rawQuery": "/* grafana dashboard=ClickHouse Queries Analysis, user=1 */\nwith \n   (intDiv(toUInt32(event_time), 300)) as query_finish,\n   (intDiv(toUInt32(query_start_time), 300)) as query_start,\n   arrayMap( i -> ( query_start + i ) * 300 * 1000, range(query_finish - query_start + 1) ) as timestamps\nSELECT \n    arrayJoin(timestamps) as t,\n    normalized_query_hash,\n    count() as m\nFROM merge(system,'^query_log')\nWHERE \n    event_date BETWEEN toDate(1736429767896 / 1000) - INTERVAL 1 DAY AND toDate(1736516167896 / 1000) + INTERVAL 1 DAY\n    AND event_time BETWEEN toDateTime(1736429767896 / 1000) - INTERVAL 20 MINUTE AND  toDateTime(1736516167896 / 1000) + INTERVAL 20 MINUTE\n    AND type!=1\n     AND hostName() in ('') \n     \n     \n     \n    AND normalized_query_hash in []\n    AND t BETWEEN 1736429767896  AND 1736516167896\nGROUP BY normalized_query_hash, t\nORDER BY count(t) OVER(PARTITION BY normalized_query_hash) DESC, sum(m) OVER(PARTITION BY normalized_query_hash) DESC\nLIMIT 200 BY t",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "By user",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribution by user",
     "type": "status-history",
     "description": "Shows selected metric ($metric) distribution by initial user, based on the query_log data",
     "gridPos": { "h": 26, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "system",
       "dateColDataType": "event_date",
       "dateTimeColDataType": "event_time",
       "dateTimeType": "DATETIME",
       "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
       "query": "with \n   (intDiv(toUInt32(event_time), $interval)) as query_finish,\n   (intDiv(toUInt32(query_start_time), $interval)) as query_start,\n   arrayMap( i -> ( query_start + i ) * $interval * 1000, range(query_finish - query_start + 1) ) as timestamps\nSELECT \n    arrayJoin(timestamps) as t,\n    initial_user as u,\n    ${metric:raw} as m\nFROM clusterAllReplicas('{cluster}', merge(system,'^query_log'))\nWHERE \n    event_date BETWEEN toDate($__from / 1000) - INTERVAL 1 DAY AND toDate($__to / 1000) + INTERVAL 1 DAY\n    AND event_time BETWEEN toDateTime($__from / 1000) - INTERVAL 20 MINUTE AND toDateTime($__to / 1000) + INTERVAL 20 MINUTE\n    AND type!=1\n    $conditionalTest(AND hostName() in ($hostname),$hostname)\n    $conditionalTest(AND query_kind in ($query_kind),$query_kind)\n    $conditionalTest(AND exception_code in ($exception_code),$exception_code)\n    $conditionalTest(AND initial_user in ($user),$user)\n    $conditionalTest(AND normalized_query_hash in [$query_hash],$query_hash)\n    AND t BETWEEN $__from  AND $__to\nGROUP BY u,t\nORDER BY count(t) OVER(PARTITION BY u) DESC, sum(m) OVER(PARTITION BY u) DESC \nLIMIT 100 BY t\nSETTINGS skip_unavailable_shards=1",
       "round": "0s",
       "table": "query_log"
      }
     ]
    }
   ]
  },
  {
   "title": "By host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribution by host",
     "type": "status-history",
     "description": "Shows selected metric ($metric) distribution by hosts, based on the query_log data",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "system",
       "dateColDataType": "event_date",
       "dateTimeColDataType": "event_time",
       "dateTimeType": "DATETIME",
       "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
       "query": "with \n   (intDiv(toUInt32(event_time), $interval)) as query_finish,\n   (intDiv(toUInt32(query_start_time), $interval)) as query_start,\n   arrayMap( i -> ( query_start + i ) * $interval * 1000, range(query_finish - query_start + 1) ) as timestamps\nSELECT \n    arrayJoin(timestamps) as t,\n    hostName() as host,\n    ${metric:raw} as m\nFROM clusterAllReplicas('{cluster}', merge(system,'^query_log'))\nWHERE \n    event_date BETWEEN toDate($__from / 1000) - INTERVAL 1 DAY AND toDate($__to / 1000) + INTERVAL 1 DAY\n    AND event_time BETWEEN toDateTime($__from / 1000) - INTERVAL 20 MINUTE AND  toDateTime($__to / 1000) + INTERVAL 20 MINUTE\n    AND type!=1\n    $conditionalTest(AND hostName() in ($hostname),$hostname)\n    $conditionalTest(AND query_kind in ($query_kind),$query_kind)\n    $conditionalTest(AND exception_code in ($exception_code),$exception_code)\n    $conditionalTest(AND initial_user in ($user),$user)\n    $conditionalTest(AND normalized_query_hash in ($query_hash),$query_hash)\n    AND t BETWEEN $__from  AND $__to\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
       "round": "0s",
       "table": "query_log"
      }
     ]
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "ProfileEvent_OSCPUVirtualTimeMicroseconds from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  avg(m) / 1000000\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(ProfileEvent_OSCPUVirtualTimeMicroseconds) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "MemoryTracking",
   "type": "timeseries",
   "description": "CurrentMetric_MemoryTracking from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(CurrentMetric_MemoryTracking) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "OSReadBytes /  OSWriteBytes (per second)",
   "type": "timeseries",
   "description": "ProfileEvent_OSReadBytes and ProfileEvent_OSWriteBytes  from system.metric_log",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  'Read ' || host as h,\n  avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(ProfileEvent_OSReadBytes) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY h,t\nORDER BY h,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  'Write ' || host as h,\n  - avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(ProfileEvent_OSWriteBytes) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY h,t\nORDER BY h,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "OSReadChars /  OSWriteChars (per second)",
   "type": "timeseries",
   "description": "ProfileEvent_OSReadChars and ProfileEvent_OSWriteChars  (includes page cache) from system.metric_log ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  'Read ' || host as h,\n  avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(ProfileEvent_OSReadChars) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY h,t\nORDER BY h,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  'Write ' || host as h,\n  - avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(ProfileEvent_OSWriteChars) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY h,t\nORDER BY h,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "timeseries",
   "description": "ProfileEvent_OSIOWaitMicroseconds from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  avg(m) / 1000000\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(ProfileEvent_OSIOWaitMicroseconds) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "CPUWait",
   "type": "timeseries",
   "description": "ProfileEvent_OSCPUWaitMicroseconds from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  avg(m) / 1000000\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(ProfileEvent_OSCPUWaitMicroseconds) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "LoadAverage1",
   "type": "timeseries",
   "description": "LoadAverage1  from asynchronous_metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT \n    $timeSeries as t,\n    hostName() as host,\n    max(value) as LoadAverage1\nFROM clusterAllReplicas('{cluster}', merge(system,'^asynchronous_metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nAND metric = 'LoadAverage1'\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "asynchronous_metric_log"
    }
   ]
  },
  {
   "title": "Network: Receive & Send",
   "type": "timeseries",
   "description": "NetworkReceiveBytes and  NetworkSendBytes  from asynchronous_metric_log",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT \n    $timeSeries as t,\n    'Receive ' || host as h,\n    max(val) as v\nFROM \n(\n    SELECT \n        event_time,\n        hostName() as host,\n        anyIf(value, metric LIKE 'NetworkReceiveBytes%') / anyIf(value, metric = 'AsynchronousMetricsUpdateInterval')  as val\n    FROM clusterAllReplicas('{cluster}', merge(system,'^asynchronous_metric_log'))\n    WHERE $timeFilter\n    $conditionalTest(AND hostName() in ($hostname),$hostname)\n    AND (metric LIKE 'NetworkReceiveBytes%' OR metric = 'AsynchronousMetricsUpdateInterval')\n    GROUP BY host,event_time\n)\nGROUP BY h,t\nORDER BY h,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "asynchronous_metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT \n    $timeSeries as t,\n    'Send ' || host as h,\n    - max(val) as v\nFROM \n(\n    SELECT \n        event_time,\n        hostName() as host,\n        anyIf(value, metric LIKE 'NetworkSendBytes%') / anyIf(value, metric = 'AsynchronousMetricsUpdateInterval')  as val\n    FROM clusterAllReplicas('{cluster}', merge(system,'^asynchronous_metric_log'))\n    WHERE $timeFilter\n    $conditionalTest(AND hostName() in ($hostname),$hostname)\n    AND (metric LIKE 'NetworkSendBytes%' OR metric = 'AsynchronousMetricsUpdateInterval')\n    GROUP BY host,event_time\n)\nGROUP BY h,t\nORDER BY h,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "asynchronous_metric_log"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "CurrentMetric_TCPConnection, CurrentMetric_HTTPConnection,  CurrentMetric_InterserverConnection and CurrentMetric_MySQLConnection from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  max(_metric) as metric\nFROM \n(\nWITH \n    arrayJoin([(CurrentMetric_TCPConnection, 'TCP'), (CurrentMetric_HTTPConnection,'HTTP'), (CurrentMetric_InterserverConnection,'Interserver'), (CurrentMetric_MySQLConnection,'MySQL') ] ) as m\nSELECT \n    event_time,\n    m.2 || ' ' || hostName() as host,\n    sum(m.1) AS _metric\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Queries Started",
   "type": "timeseries",
   "description": "ProfileEvent_Query from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  avg(m) \nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(ProfileEvent_Query) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Running Queries",
   "type": "timeseries",
   "description": "CurrentMetric_Query from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT \n    $timeSeries as t,\n    hostName() as host,\n    max(CurrentMetric_Query) as QueriesRunning\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE \n$timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Merges running",
   "type": "timeseries",
   "description": "CurrentMetric_Merge from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(CurrentMetric_Merge) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Mutations running",
   "type": "timeseries",
   "description": "CurrentMetric_PartMutation from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(CurrentMetric_PartMutation) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Moves running",
   "type": "timeseries",
   "description": "CurrentMetric_Move from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(CurrentMetric_Move) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "DistributedSend running",
   "type": "timeseries",
   "description": "CurrentMetric_DistributedSend from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(CurrentMetric_DistributedSend) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "ReplicatedFetch & ReplicatedSend running",
   "type": "timeseries",
   "description": "CurrentMetric_ReplicatedFetch and CurrentMetric_ReplicatedSend from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  'Fetch ' || host as h,\n  avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(CurrentMetric_ReplicatedFetch) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY h,t\nORDER BY h,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  'Send ' || host as h,\n  -avg(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(CurrentMetric_ReplicatedSend) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY h,t\nORDER BY h,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "ReplicatedChecks running",
   "type": "timeseries",
   "description": "CurrentMetric_ReplicatedChecks from system.metric_log",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 130 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT    \n  (intDiv(toUInt32(event_time), $interval)) * $interval * 1000 as t,\n  host,\n  max(m)\nFROM \n(\nSELECT \n    event_time,\n    hostName() as host,\n    sum(CurrentMetric_ReplicatedChecks) AS m\nFROM clusterAllReplicas('{cluster}', merge(system,'^metric_log'))\nWHERE $timeFilter\n$conditionalTest(AND hostName() in ($hostname),$hostname)\nGROUP BY host,event_time\n)\nGROUP BY host,t\nORDER BY host,t\nSETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "metric_log"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 26, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "database": "system",
       "dateColDataType": "event_date",
       "dateTimeColDataType": "event_time",
       "dateTimeType": "DATETIME",
       "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',system.query_log)</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_kind'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_kind'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
       "query": "SELECT \n    toString(normalized_query_hash) as query_hash,\n    argMax(query_id, cputime) AS sample_query_id,\n    replace(argMax(query, cputime), '\\n', ' ') AS query,\n    count() as cnt,\n    sum(query_duration_ms) / 1000 AS QueriesDuration, /* wall clock */\n    sum(ProfileEvents['OSCPUVirtualTimeMicroseconds'] as cputime) / 1000000 AS OSCPUVirtualTime, /* similar to usertime + system time */\n    sum(ProfileEvents['OSIOWaitMicroseconds']) / 1000000 AS OSIOWaitTime, /* IO waits, usually disks - that metric is 'orthogonal' to other */ \n    quantile(0.97)(memory_usage) as MemoryUsageQ97 ,\n    sum(read_rows) AS ReadRows,\n    sum(read_bytes) AS ReadBytes,\n    sum(ProfileEvents['NetworkReceiveBytes']) AS NetworkReceiveBytes,\n    sum(ProfileEvents['NetworkSendBytes']) AS NetworkSendBytes,\n    sum(written_rows) AS WrittenRows,\n    sum(written_bytes) AS WrittenBytes, /* */\n    sum(result_rows) AS ResultRows,\n    sum(result_bytes) AS ResultBytes,\n    arrayStringConcat(groupUniqArrayIf(5)( errorCodeToName(exception_code), exception_code <> 0 ), ',') AS exceptions,\n    arrayStringConcat(groupUniqArray(5)( initial_user ), ',') AS users,\n    sum(ProfileEvents['DiskReadElapsedMicroseconds']) / 1000000 AS DiskReadTime,\n    sum(ProfileEvents['DiskWriteElapsedMicroseconds']) / 1000000 AS DiskWriteTime,\n    sum(ProfileEvents['RealTimeMicroseconds']) / 1000000 AS RealTime,  /* same as above but x number of thread */\n    sum(ProfileEvents['UserTimeMicroseconds']) / 1000000 AS UserTime,  /* time when our query was doin some cpu-insense work, creating cpu load */\n    sum(ProfileEvents['SystemTimeMicroseconds']) / 1000000 AS SystemTime, /* time spend on waiting for some system operations */\n    sum(ProfileEvents['NetworkSendElapsedMicroseconds']) / 1000000 AS NetworkSendTime, /* check the other side of the network! */\n    sum(ProfileEvents['NetworkReceiveElapsedMicroseconds']) / 1000000 AS NetworkReceiveTime, /* check the other side of the network! */\n    sum(ProfileEvents['SelectedParts']) as SelectedParts,\n    sum(ProfileEvents['SelectedRanges']) as SelectedRanges,\n    sum(ProfileEvents['SelectedMarks']) as SelectedMarks,\n    sum(ProfileEvents['SelectedRows']) as SelectedRows,  /* those may different from read_rows - here the number or rows potentially matching the where conditions, not neccessary all will be read */\n    sum(ProfileEvents['SelectedBytes']) as SelectedBytes,\n    sum(ProfileEvents['FileOpen']) as FileOpen,\n    sum(ProfileEvents['ZooKeeperTransactions']) as ZooKeeperTransactions,\n    sum(ProfileEvents['OSReadBytes'] ) as OSReadBytesExcludePageCache,\n    sum(ProfileEvents['OSWriteBytes'] ) as OSWriteBytesExcludePageCache,\n    sum(ProfileEvents['OSReadChars'] ) as OSReadBytesIncludePageCache,\n    sum(ProfileEvents['OSWriteChars'] ) as OSWriteCharsIncludePageCache,\n    anyIf(exception, exception<>'') as exception_sample,\n    min(event_time) as min_event_time,\n    max(event_time) as max_event_time\nFROM clusterAllReplicas('{cluster}', merge(system,'^query_log'))\nWHERE \nhostName() IN ($hostname)\nAND $timeFilter AND type in (2,4)-- QueryFinish, ExceptionWhileProcessing\nand normalized_query_hash IN [$query_hash]\nGROUP BY normalized_query_hash\nORDER BY cnt DESC\nSETTINGS skip_unavailable_shards=1",
       "round": "0s",
       "table": "query_log"
      }
     ]
    }
   ]
  }
 ]
}