{
 "title": "$conditionalTest 3 params issue 869",
 "description": "reproduce https://github.com/Altinity/clickhouse-grafana/issues/869",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Tenant",
    "query": {
     "query": "SELECT 'tenant1' \nUNION ALL\nSELECT 'tenant2'\n"
    }
   },
   { "name": "TextFilter" }
  ]
 },
 "panels": [
  {
   "title": "2 params conditionalTest with query variable",
   "type": "timeseries",
   "description": "2 params conditionalTest: when Tenant has a value, include filter; when empty, remove filter",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "query": "with\ncte2 as (\n  select cte2_field,\n         blatenant \"Alias\"\n  FROM\n    cte2_table\n  WHERE 1\n    $conditionalTest(AND cte2_tenant in ($Tenant), $Tenant)\n)\nselect * EXCEPT (\"excluded_column\")\nFROM cte2",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "3 params conditionalTest with query variable",
   "type": "timeseries",
   "description": "3 params conditionalTest: when Tenant has a value, use SQL_if; when empty, use SQL_else",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "query": "with\ncte2 as (\n  select cte2_field,\n         blatenant \"Alias\"\n  FROM\n    cte2_table\n  WHERE 1\n    $conditionalTest(AND cte2_tenant in ($Tenant), AND cte2_tenant = 'default_tenant', $Tenant)\n)\nselect * EXCEPT (\"excluded_column\")\nFROM cte2",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  },
  {
   "title": "3 params conditionalTest with textbox variable",
   "type": "timeseries",
   "description": "3 params conditionalTest with textbox: when TextFilter is empty, use SQL_else; when has value, use SQL_if",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "query": "SELECT 1 WHERE 1\n$conditionalTest(AND name = '$TextFilter', AND name IS NOT NULL, $TextFilter)",
     "round": "0s",
     "table": "test_grafana"
    }
   ]
  }
 ]
}