{
 "title": "Dashboard for screenshots",
 "description": "https://github.com/Altinity/clickhouse-grafana/issues/514",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests by OS",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/514",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(OSName, sum(req_count) c)\r\nFROM requests\r\nINNER JOIN oses USING (OS)\r\n",
     "rawQuery": "/* grafana dashboard=OS columns, user=1 */\nSELECT t, groupArray((OSName, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 30) * 30) * 1000 AS t, OSName, sum(req_count) c FROM requests\r\nANY INNER JOIN oses USING (OS) WHERE EventTime >= toDateTime(1715149231) AND EventTime <= toDateTime(1715170831) GROUP BY t, OSName ORDER BY t, OSName) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "requests"
    }
   ]
  },
  {
   "title": "Requests by User",
   "type": "grafana-piechart-panel",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/514",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 1 AS t, UserName, sum(req_count*randUniform(40,100)) req\r\nFROM $table\r\nWHERE $timeFilter\r\nGROUP BY UserName\r\nORDER BY req DESC\r\nLIMIT 5",
     "rawQuery": "/* grafana dashboard=OS columns, user=1 */\nSELECT 1 AS t, UserName, sum(req_count) req\r\nFROM default.requests\r\nWHERE EventTime >= toDateTime(1715154784) AND EventTime <= toDateTime(1715176384)\r\nGROUP BY UserName\r\nORDER BY req DESC\r\nLIMIT 5",
     "round": "0s",
     "table": "requests"
    },
    {
     "database": "default",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    1 AS t, /* fake timestamp value */\r\n    UserName,\r\n    sum(req_count) AS req\r\nFROM requests\r\nGROUP BY t, UserName\r\nORDER BY req DESC\r\nLIMIT 5,10000000000000 /* select some ridiculous number after first 5 */\r\n",
     "rawQuery": "/* grafana dashboard=OS columns, user=1 */\nSELECT 1 AS t, UserName, sum(req_count) req\r\nFROM default.requests\r\nWHERE EventTime >= toDateTime(1715154713) AND EventTime <= toDateTime(1715176313)\r\nGROUP BY UserName\r\nORDER BY req DESC\r\nLIMIT 5",
     "round": "0s",
     "table": "requests"
    }
   ]
  },
  {
   "title": "Requests by User",
   "type": "table",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/514",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT UserName, sum(req_count) req\r\nFROM $table\r\nWHERE $timeFilter\r\nGROUP BY UserName\r\n",
     "rawQuery": "/* grafana dashboard=OS columns, user=1 */\nSELECT t, groupArray((OSName, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 10) * 10) * 1000 AS t, OSName, sum(req_count) c FROM requests\r\nINNER JOIN oses USING (OS) WHERE EventTime >= toDateTime(1715164603) AND EventTime <= toDateTime(1715164953) GROUP BY t, OSName ORDER BY t, OSName) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "requests"
    }
   ]
  },
  {
   "title": "Vertical Histogram",
   "type": "barchart",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/514",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \r\n now() AS t,\r\n 100 AS small,\r\n 500 AS medium,\r\n 1000 AS big\r\n\r\n",
     "rawQuery": "/* grafana dashboard=OS columns, user=1 */\nSELECT \r\n 100 AS small,\r\n 500 AS medium,\r\n 1000 AS big",
     "round": "0s",
     "table": "requests"
    }
   ]
  }
 ]
}