{
 "title": "$delta, $deltaColumns, $increase, $increaseColumns",
 "description": "dashboard for https://github.com/Altinity/clickhouse-grafana/issues/455",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "$deltaColumns",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/455",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$deltaColumns(category AS category, counter)\nFROM $table",
     "rawQuery": "SELECT t, groupArray((category, max_0_Delta)) AS groupArr FROM ( SELECT t, category, if(neighbor(category,-1,category) != category, 0, runningDifference(max_0)) AS max_0_Delta FROM ( SELECT (intDiv(toUInt32(\"d\"), 20) * 20) * 1000 AS t, category AS category, max(counter) AS max_0 FROM default.test_rate_and_per_seconds WHERE \"d\" >= toDateTime(1669117084) AND \"d\" <= toDateTime(1669138684) GROUP BY t, category ORDER BY category, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_rate_and_per_seconds"
    }
   ]
  },
  {
   "title": "$increaseColumns",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/455",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increaseColumns(category AS category, counter)\nFROM $table",
     "rawQuery": "SELECT t, groupArray((category, max_0_Increase)) AS groupArr FROM ( SELECT t, category, if(runningDifference(max_0) < 0 OR neighbor(category,-1,category) != category, 0, runningDifference(max_0)) AS max_0_Increase FROM ( SELECT (intDiv(toUInt32(\"d\"), 20) * 20) * 1000 AS t, category AS category, max(counter) AS max_0 FROM default.test_rate_and_per_seconds WHERE \"d\" >= toDateTime(1669117225) AND \"d\" <= toDateTime(1669138825) GROUP BY t, category ORDER BY category, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_rate_and_per_seconds"
    }
   ]
  },
  {
   "title": "$delta",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/455",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$delta(counter)\nFROM $table",
     "rawQuery": "SELECT t, runningDifference(max_0) AS max_0_Delta FROM ( SELECT (intDiv(toUInt32(\"d\"), 20) * 20) * 1000 AS t, max(counter) AS max_0 FROM default.test_rate_and_per_seconds WHERE \"d\" >= toDateTime(1669117168) AND \"d\" <= toDateTime(1669138768) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_rate_and_per_seconds"
    }
   ]
  },
  {
   "title": "$increase",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/455",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increase(counter)\nFROM $table",
     "rawQuery": "SELECT t, if(runningDifference(max_0) < 0, 0, runningDifference(max_0)) AS max_0_Increase FROM ( SELECT (intDiv(toUInt32(\"d\"), 2) * 2) * 1000 AS t, max(counter) AS max_0 FROM default.test_rate_and_per_seconds WHERE \"d\" >= toDateTime(1669100930) AND \"d\" <= toDateTime(1669103000) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_rate_and_per_seconds"
    }
   ]
  }
 ]
}