{
 "title": "grafana labs dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "query": "SELECT DISTINCT Name FROM default.test_alerts"
   },
   { "name": "adhoc_variable" }
  ]
 },
 "panels": [
  {
   "title": "query builder",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(EventTime) as \"time\", EventTime, sum(Value) FROM \"default\".\"test_alerts\" GROUP BY EventTime, time ORDER BY EventTime ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "query editor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(EventTime) as time, Name, sum(Value) \r\nFROM default.test_alerts \r\nWHERE $__timeFilter(EventTime) \r\nAND Name IN (${service_name})\r\nGROUP BY Name, time \r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Logs + query builder",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT * FROM default.test_logs WHERE   ( event_time  >= $__fromTime AND event_time <= $__toTime )"
    }
   ]
  }
 ]
}