{
 "title": "window functions",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "$delta",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$delta(Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, max_0 - lagInFrame(max_0,1,0) OVER () AS max_0_Delta FROM ( SELECT (intDiv(toUInt32(EventTime), 30) * 30) * 1000 AS t, max(Valu) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733547869) AND EventDate <= toDate(1733569469) AND EventTime >= toDateTime(1733547869) AND EventTime <= toDateTime(1733569469) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$delta - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$delta(Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, runningDifference(max_0) AS max_0_Delta FROM ( SELECT (intDiv(toUInt32(EventTime), 30) * 30) * 1000 AS t, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733547869) AND EventDate <= toDate(1733569469) AND EventTime >= toDateTime(1733547869) AND EventTime <= toDateTime(1733569469) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$deltaColumns",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$deltaColumns(Name, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, groupArray((deltaColumns, max_0_Delta)) AS groupArr FROM ( SELECT t, deltaColumns, if(lagInFrame(deltaColumns,1,deltaColumns) OVER () != deltaColumns, 0, max_0 - lagInFrame(max_0,1,0) OVER ()) AS max_0_Delta FROM ( SELECT (intDiv(toUInt32(EventTime), 30) * 30) * 1000 AS t, Name AS deltaColumns, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733553293) AND EventDate <= toDate(1733574893) AND EventTime >= toDateTime(1733553293) AND EventTime <= toDateTime(1733574893) GROUP BY t, deltaColumns ORDER BY deltaColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$deltaColumns - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$deltaColumns(Name, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, groupArray((deltaColumns, max_0_Delta)) AS groupArr FROM ( SELECT t, deltaColumns, if(neighbor(deltaColumns,-1,deltaColumns) != deltaColumns, 0, runningDifference(max_0)) AS max_0_Delta FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name AS deltaColumns, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733553293) AND EventDate <= toDate(1733574893) AND EventTime >= toDateTime(1733553293) AND EventTime <= toDateTime(1733574893) GROUP BY t, deltaColumns ORDER BY deltaColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$deltaColumnsAggregated",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$deltaColumnsAggregated(Name, 'test2' AS subName, sum, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, Name, sum(ValueDelta) AS ValueDeltaAgg FROM (  SELECT t, Name, subName, if(lagInFrame(subName,1,subName) OVER () != subName, 0, Value - lagInFrame(Value,1,0) OVER ()) AS ValueDelta  FROM (   SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name, 'test2' AS subName, max(Value) AS Value   FROM default.test_alerts WHERE EventDate >= toDate(1733553293) AND EventDate <= toDate(1733574893) AND EventTime >= toDateTime(1733553293) AND EventTime <= toDateTime(1733574893)   GROUP BY Name, subName, t    ORDER BY Name, subName, t  ) ) GROUP BY Name, t ORDER BY Name, t",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$deltaColumnsAggregated - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$deltaColumnsAggregated(Name, 'test2' AS subName, sum, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, groupArray((deltaColumns, max_0_Delta)) AS groupArr FROM ( SELECT t, deltaColumns, if(neighbor(deltaColumns,-1,deltaColumns) != deltaColumns, 0, runningDifference(max_0)) AS max_0_Delta FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name AS deltaColumns, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733553293) AND EventDate <= toDate(1733574893) AND EventTime >= toDateTime(1733553293) AND EventTime <= toDateTime(1733574893) GROUP BY t, deltaColumns ORDER BY deltaColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$increase",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increase(Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\n$increas(Value) FROM default.test_alerts",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$increase - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increase(Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, if(runningDifference(max_0) < 0, 0, runningDifference(max_0)) AS max_0_Increase FROM ( SELECT (intDiv(toUInt32(EventTime), 30) * 30) * 1000 AS t, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733548152) AND EventDate <= toDate(1733569752) AND EventTime >= toDateTime(1733548152) AND EventTime <= toDateTime(1733569752) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$increaseColumns",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increaseColumns(Name, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, groupArray((increaseColumns, max_0_Increase)) AS groupArr FROM ( SELECT t, increaseColumns, if((max_0 - lagInFrame(max_0,1,0) OVER ()) < 0 OR lagInFrame(increaseColumns,1,increaseColumns) != increaseColumns, 0, max_0 - lagInFrame(max_0,1,0) OVER ()) AS max_0_Increase FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name AS increaseColumns, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733551938) AND EventDate <= toDate(1733573538) AND EventTime >= toDateTime(1733551938) AND EventTime <= toDateTime(1733573538) GROUP BY t, increaseColumns ORDER BY increaseColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$increaseColumns - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increaseColumns(Name, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, if(runningDifference(max_0) < 0, 0, runningDifference(max_0)) AS max_0_Increase FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733551938) AND EventDate <= toDate(1733573538) AND EventTime >= toDateTime(1733551938) AND EventTime <= toDateTime(1733573538) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$increaseColumnsAggregated",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increaseColumnsAggregated(Name, 'test2' AS subName, sum, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, Name, sum(ValueIncrease) AS ValueIncreaseAgg FROM (  SELECT t, Name, subName, if((Value - lagInFrame(Value,1,0) OVER ()) < 0 OR lagInFrame(subName,1,subName) OVER () != subName, nan, Value - lagInFrame(Value,1,0) OVER ()) AS ValueIncrease  FROM (   SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name, 'test2' AS subName, max(Value) AS Value   FROM default.test_alerts WHERE EventDate >= toDate(1733552907) AND EventDate <= toDate(1733574507) AND EventTime >= toDateTime(1733552907) AND EventTime <= toDateTime(1733574507)   GROUP BY Name, subName, t    ORDER BY Name, subName, t  ) ) GROUP BY Name, t ORDER BY Name, t",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$increaseColumnsAggregated - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$increaseColumnsAggregated(Name, 'test2' AS subName, sum, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, groupArray((increaseColumns, max_0_Increase)) AS groupArr FROM ( SELECT t, increaseColumns, if(runningDifference(max_0) < 0 OR neighbor(increaseColumns,-1,increaseColumns) != increaseColumns, 0, runningDifference(max_0)) AS max_0_Increase FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name AS increaseColumns, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733552907) AND EventDate <= toDate(1733574507) AND EventTime >= toDateTime(1733552907) AND EventTime <= toDateTime(1733574507) GROUP BY t, increaseColumns ORDER BY increaseColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$perSecond",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, if(max_0 - lagInFrame(max_0,1,0) OVER () < 0, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / ((t - lagInFrame(t,1,0) OVER ())/1000) ) AS max_0_PerSecond FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733548152) AND EventDate <= toDate(1733569752) AND EventTime >= toDateTime(1733548152) AND EventTime <= toDateTime(1733569752) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$perSecond - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecond(Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\n$perSecond((Value) FROM default.test_alerts",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$perSecondColumns",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecondColumns(Name, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=1 */\nSELECT t, groupArray((perSecondColumns, max_0_PerSecond)) AS groupArr FROM ( SELECT t, perSecondColumns, if((max_0 - lagInFrame(max_0,1,0) OVER ()) < 0 OR lagInFrame(perSecondColumns,1,perSecondColumns) OVER () != perSecondColumns, nan, (max_0 - lagInFrame(max_0,1,0) OVER ()) / (t/1000 - lagInFrame(t/1000,1,0) OVER ())) AS max_0_PerSecond FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name AS perSecondColumns, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733550114) AND EventDate <= toDate(1733571714) AND EventTime >= toDateTime(1733550114) AND EventTime <= toDateTime(1733571714) GROUP BY t, perSecondColumns ORDER BY perSecondColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$perSecondColumns - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecondColumns(Name, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=1 */\nSELECT t, if(runningDifference(max_0) < 0, nan, runningDifference(max_0) / runningDifference(t/1000)) AS max_0_PerSecond FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733550114) AND EventDate <= toDate(1733571714) AND EventTime >= toDateTime(1733550114) AND EventTime <= toDateTime(1733571714) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$perSecondColumnsAggregated",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecondColumnsAggregated(Name, 'test2' AS subName, sum, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=1 */\nSELECT t, Name, sum(ValuePerSecond) AS ValuePerSecondAgg FROM (  SELECT t, Name, subName, if((Value - lagInFrame(Value,1,0) OVER ()) < 0 OR lagInFrame(subName,1,subName) != subName, nan, (Value - lagInFrame(Value,1,0) OVER ()) / (t/1000 - lagInFrame(t/1000,1,0) OVER ())) AS ValuePerSecond  FROM (   SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name, 'test2' AS subName, max(Value) AS Value   FROM default.test_alerts WHERE EventDate >= toDate(1733550114) AND EventDate <= toDate(1733571714) AND EventTime >= toDateTime(1733550114) AND EventTime <= toDateTime(1733571714)   GROUP BY Name, subName, t    ORDER BY Name, subName, t  ) ) GROUP BY Name, t ORDER BY Name, t",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$perSecondColumnsAggregated - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$perSecondColumnsAggregated(Name, 'test2' AS subName, sum, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=1 */\nSELECT t, groupArray((perSecondColumns, max_0_PerSecond)) AS groupArr FROM ( SELECT t, perSecondColumns, if(runningDifference(max_0) < 0 OR neighbor(perSecondColumns,-1,perSecondColumns) != perSecondColumns, nan, runningDifference(max_0) / runningDifference(t/1000)) AS max_0_PerSecond FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name AS perSecondColumns, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733550114) AND EventDate <= toDate(1733571714) AND EventTime >= toDateTime(1733550114) AND EventTime <= toDateTime(1733571714) GROUP BY t, perSecondColumns ORDER BY perSecondColumns, t)) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$rate",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rate(sum(Value) AS vSumValue) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, vSumValu/((t - lagInFrame(t,1,0) OVER ())/1000) vSumValuRate FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, sum(Value) AS vSumValu FROM default.test_alerts WHERE EventDate >= toDate(1733548152) AND EventDate <= toDate(1733569752) AND EventTime >= toDateTime(1733548152) AND EventTime <= toDateTime(1733569752) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$rate - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rate(sum(Value) AS vSumValue) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=0 */\nSELECT t, if(runningDifference(max_0) < 0, nan, runningDifference(max_0) / runningDifference(t/1000)) AS max_0_PerSecond FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, max(Value) AS max_0 FROM default.test_alerts WHERE EventDate >= toDate(1733548152) AND EventDate <= toDate(1733569752) AND EventTime >= toDateTime(1733548152) AND EventTime <= toDateTime(1733569752) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$rateColumns",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rateColumns(Name, sum(Value) AS vSumValue) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=1 */\nSELECT t, arrayMap(a -> (a.1, a.2/(t/1000 - lagInFrame(t/1000,1,0) OVER ())), groupArr) FROM (SELECT t, groupArray((Name, vSumValue)) AS groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name, sum(Value) AS vSumValue FROM default.test_alerts WHERE EventDate >= toDate(1733550114) AND EventDate <= toDate(1733571714) AND EventTime >= toDateTime(1733550114) AND EventTime <= toDateTime(1733571714) GROUP BY t, Name ORDER BY t, Name) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$rateColumns - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rateColumns(Name, sum(Value) AS vSumValue) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=1 */\nSELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM (SELECT t, groupArray((Name, vSumValue)) AS groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name, sum(Value) AS vSumValue FROM default.test_alerts WHERE EventDate >= toDate(1733550114) AND EventDate <= toDate(1733571714) AND EventTime >= toDateTime(1733550114) AND EventTime <= toDateTime(1733571714) GROUP BY t, Name ORDER BY t, Name) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$rateColumnsAggregated",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rateColumnsAggregated(Name, if(today() % 2,'subTest1','subTest2') AS SubName, sum, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=1 */\n$rateColumnsAggregated(Name, if(today( % 2,'subTest1','subTest2') AS SubName, sum, Value) FROM default.test_alerts",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  },
  {
   "title": "$rateColumnsAggregated - without window functions",
   "type": "timeseries",
   "description": "https://github.com/Altinity/clickhouse-grafana/issues/572",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "default",
     "dateColDataType": "EventDate",
     "dateTimeColDataType": "EventTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rateColumnsAggregated(Name, if(today() % 2,'subTest1','subTest2') AS SubName, sum, Value) FROM $table",
     "rawQuery": "/* grafana dashboard=window functions, user=1 */\nSELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM (SELECT t, groupArray((Name, vSumValue)) AS groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 20) * 20) * 1000 AS t, Name, sum(Value) AS vSumValue FROM default.test_alerts WHERE EventDate >= toDate(1733550114) AND EventDate <= toDate(1733571714) AND EventTime >= toDateTime(1733550114) AND EventTime <= toDateTime(1733571714) GROUP BY t, Name ORDER BY t, Name) GROUP BY t ORDER BY t)",
     "round": "0s",
     "table": "test_alerts"
    }
   ]
  }
 ]
}