{
 "title": "postgres dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "array_var",
    "query": "SELECT DISTINCT ARRAY_TO_STRING(ARRAY[service_name, ' test array'], ',') FROM test_grafana"
   }
  ]
 },
 "panels": [
  {
   "title": "PosrgeSQL + Table numeric 32E11 interperations",
   "type": "table",
   "description": "see https://github.com/Vertamedia/clickhouse-grafana/issues/254",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  '32E11' AS t1,\n  '32E1' AS t2,\n  'test' AS t3\nFROM test_grafana\nWHERE\n  $__timeFilter(event_time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PostgreSQL alert test",
   "type": "graph",
   "description": "https://github.com/Vertamedia/clickhouse-grafana/issues/384",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(event_time,$__interval),\n  sum(too_big_value) AS \"too_big_value\"\nFROM test_grafana\nWHERE\n  $__timeFilter(event_time)\n  /* AND ARRAY_TO_STRING(ARRAY[service_name, ' test array'], ',') IN (${array_var})  */\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PostgreSQL array template varible test",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(event_time,$__interval),\n  sum(too_big_value) AS \"too_big_value\"\nFROM test_grafana\nWHERE\n  $__timeFilter(event_time)\n  AND ARRAY_TO_STRING(ARRAY[service_name, ' test array'], ',') IN (${array_var})\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}