{
 "title": "test timezone",
 "description": "reproducing for https://github.com/Altinity/clickhouse-grafana/issues/625",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Traces with TimeZone",
   "type": "traces",
   "description": "reproduce https://github.com/Altinity/clickhouse-grafana/issues/625",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "finish_date",
     "dateTimeColDataType": "intDiv(finish_time_us,1000000)",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    trace_id AS traceID,\r\n    span_id AS spanID,\r\n    operation_name AS operationName,\r\n    parent_span_id AS parentSpanID,\r\n    'clickhouse' AS serviceName,\r\n    intDiv(finish_time_us - start_time_us, 1000) AS duration,\r\n    toDateTime64(start_time_us/1000000,3,'Europe/Moscow') AS startTime,\r\n    attribute AS tags,\r\n    map('hostName',hostname) AS serviceTags\r\nFROM\r\n   $table\r\nWHERE $timeFilter\r\nORDER BY traceID, startTime",
     "rawQuery": "/* grafana dashboard=test timezone, user=0 */\nSELECT\r\n    trace_id AS traceID,\r\n    span_id AS spanID,\r\n    operation_name AS operationName,\r\n    parent_span_id AS parentSpanID,\r\n    'clickhouse' AS serviceName,\r\n    intDiv(finish_time_us - start_time_us, 1000) AS duration,\r\n    toDateTime64(start_time_us/1000000,3,'Europe/Moscow) AS startTime,\r\n    attribute AS tags,\r\n    map('hostName',hostname) AS serviceTags\r\nFROM\r\n   system.opentelemetry_span_log\r\nWHERE finish_date >= toDate(1729083528) AND finish_date <= toDate(1729084428) AND intDiv(finish_time_us,1000000) >= 1729083528 AND intDiv(finish_time_us,1000000) <= 1729084428\r\nORDER BY traceID, startTime",
     "round": "0s",
     "table": "opentelemetry_span_log"
    }
   ]
  },
  {
   "title": "Time Zone DateTime - tm ",
   "type": "timeseries",
   "description": "Try to reproduce https://github.com/Altinity/clickhouse-grafana/issues/625",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "test",
     "dateColDataType": "dt",
     "dateTimeColDataType": "tm",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT toStartOfMinute(tm) as t, sum(v) FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=test timezone, user=0 */\nSELECT (intDiv(toUInt32(tm), 60) * 60) * 1000 as t, sum(v) FROM test.test_timezone WHERE dt >= toDate(1728922254) AND dt <= toDate(1729008654) AND tm >= toDateTime(1728922254) AND tm <= toDateTime(1729008654) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "test_timezone"
    }
   ]
  },
  {
   "title": "Test Log with DateTime64 Time zone",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "test",
     "dateColDataType": "dt",
     "dateTimeColDataType": "tm64",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT tm64 AS timestamp, log AS message FROM $table WHERE $timeFilter",
     "rawQuery": "/* grafana dashboard=test timezone, user=0 */\nSELECT t64 AS timestamp, log AS message FROM test.test_timezone WHERE dt >= toDate(1728624977) AND dt <= toDate(1728711377) AND tm64 >= toDateTime64(1728624977, 3) AND tm64 <= toDateTime64(1728711377, 3)",
     "round": "0s",
     "table": "test_timezone"
    }
   ]
  }
 ]
}