{
 "title": "Ontime Database Carrier and Airport Stats",
 "description": "ClickHouse dashhboard for sample data from the Airline Carrier On-Time dataset from US Bureau of Transportation Statistics.  ",
 "time": { "from": "2020-01-01T05:00:00.000Z", "to": "2020-12-31T05:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "carrier",
    "label": "Carrier",
    "query": "select distinct Carrier from default.ontime order by Carrier"
   }
  ]
 },
 "panels": [
  {
   "title": "Flight Statistics for All Carriers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total Carriers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "FlightDate",
     "dateTimeType": "DATETIME",
     "formatAs": "time_series",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT countDistinct(Carrier) FROM $table",
     "rawQuery": "/* grafana dashboard=Ontime Database Carrier and Airport Stats, user=1 */\nSELECT countDistinct(Carrier) FROM default.ontime",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Airports by Arrivals and % Delay",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Dest, Flights, DelayPercentage, dest.Name, dest.Latitude, dest.Longitude \r\nFROM \r\n(\r\n  SELECT Dest, count() AS Flights, sum(ArrDel15)/Flights*100.0 as DelayPercentage FROM ontime\r\n  WHERE $timeFilter \r\n  GROUP BY Dest\r\n) AS o \r\nJOIN airports AS dest ON o.Dest = dest.IATA \r\n",
     "rawQuery": "/* grafana dashboard=Ontime Database Carrier and Airport Stats, user=1 */\nSELECT Dest, Flights, DelayPercentage, dest.Name, dest.Latitude, dest.Longitude,\r\nmultiIf(DelayPercentage < 3, 'green', DelayPercentage < 10, 'yellow', 'red') AS Color \r\nFROM \r\n(\r\n  SELECT Dest, count() AS Flights, sum(ArrDel15)/Flights*100.0 as DelayPercentage FROM ontime\r\n  WHERE toDateTime(FlightDate) >= toDateTime(1577865600) AND toDateTime(FlightDate) <= toDateTime(1609488000) \r\n  GROUP BY Dest\r\n) AS o \r\nJOIN airports AS dest ON o.Dest = dest.IATA",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Total Flights for All Carriers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count() FROM $table WHERE $timeFilter",
     "rawQuery": "/* grafana dashboard=Ontime Database Carrier and Airport Stats, user=1 */\nSELECT count() FROM default.ontime WHERE FlightDate >= toDate(1577865600) AND FlightDate <= toDate(1609488000) AND toDateTime(FlightDate) >= toDateTime(1577865600) AND toDateTime(FlightDate) <= toDateTime(1609488000) and Carrier = '9E'",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Number of Flights by All Carriers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formatAs": "time_series",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Carrier, count() Flights\r\n  FROM $table \r\n WHERE $timeFilter \r\n GROUP BY t, Carrier ORDER BY t, Carrier ",
     "rawQuery": "/* grafana dashboard=Ontime Database Carrier and Airport Stats, user=1 */\nSELECT (intDiv(toUInt32(toDateTime(FlightDate)), 21600) * 21600) * 1000 as t, Carrier, count() Flights\r\n  FROM default.ontime \r\n WHERE FlightDate >= toDate(1672560000) AND FlightDate <= toDate(1704095999) AND toDateTime(FlightDate) >= toDateTime(1672560000) AND toDateTime(FlightDate) <= toDateTime(1704095999) \r\n GROUP BY t, Carrier ORDER BY t, Carrier",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Cancelled Flights over Time",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Carrier, sum(Cancelled)/count(*)*100.0 as \"CarrierAverage\"\n  FROM $table \n WHERE $timeFilter \n GROUP BY t, Carrier ORDER BY t, Carrier ",
     "rawQuery": "/* grafana dashboard=Ontime Database Carrier and Airport Stats, user=1 */\nSELECT (intDiv(toUInt32(toDateTime(FlightDate)), 21600) * 21600) * 1000 as t, sum(Cancelled)/count(*)*100.0 as \"Carrier Average\"\n  FROM default.ontime \n WHERE Carrier = 'WN'\n   AND FlightDate >= toDate(1262332800) AND FlightDate <= toDate(1293868800) AND toDateTime(FlightDate) >= toDateTime(1262332800) AND toDateTime(FlightDate) <= toDateTime(1293868800) \n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Flight Statistics for Single Carrier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Total Flights for Carrier ${carrier}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count() FROM $table WHERE $timeFilter and Carrier = '$carrier'",
     "rawQuery": "/* grafana dashboard=Ontime Database Carrier and Airport Stats, user=1 */\nSELECT count() FROM default.ontime WHERE FlightDate >= toDate(1577865600) AND FlightDate <= toDate(1718810559) AND toDateTime(FlightDate) >= toDateTime(1577865600) AND toDateTime(FlightDate) <= toDateTime(1718810559)",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Per Carrier Airports by Arrivals and % Delay",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 21 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Dest, Flights, DelayPercentage, dest.Name, dest.Latitude, dest.Longitude \r\nFROM \r\n(\r\n  SELECT Dest, count() AS Flights, sum(ArrDel15)/Flights*100.0 as DelayPercentage FROM ontime\r\n  WHERE $timeFilter and Carrier = '$carrier'\r\n  GROUP BY Dest\r\n) AS o \r\nJOIN airports AS dest ON o.Dest = dest.IATA \r\n",
     "rawQuery": "/* grafana dashboard=Ontime Database Carrier and Airport Stats, user=1 */\nSELECT Dest, Flights, DelayPercentage, dest.Name, dest.Latitude, dest.Longitude \r\nFROM \r\n(\r\n  SELECT Dest, count() AS Flights, sum(ArrDel15)/Flights*100.0 as DelayPercentage FROM ontime\r\n  WHERE toDateTime(FlightDate) >= toDateTime(1577865600) AND toDateTime(FlightDate) <= toDateTime(1609488000) \r\n  GROUP BY Dest\r\n) AS o \r\nJOIN airports AS dest ON o.Dest = dest.IATA",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Selected Carrier Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formatAs": "time_series",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT '$carrier'",
     "rawQuery": "/* grafana dashboard=Ontime Database Carrier and Airport Stats, user=1 */\nSELECT '9E'",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Number of Flights Operated by Carrier",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count(*) Flights \n  FROM $table \n WHERE Carrier = '$carrier'\n   AND $timeFilter \n GROUP BY t ORDER BY t ",
     "rawQuery": "SELECT (intDiv(toUInt32(toDateTime(FlightDate)), 21600) * 21600) * 1000 as t, count(*) Flights \n  FROM default.ontime \n WHERE Carrier = '9E'\n   AND FlightDate >= toDate(1555911848) AND FlightDate <= toDate(1582094648) AND toDateTime(FlightDate) >= toDateTime(1555911848) AND toDateTime(FlightDate) <= toDateTime(1582094648) \n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Percentage of Delayed Arrivals",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, sum(ArrDel15)/count(*)*100.0 as \"Carrier Average\"\n  FROM $table \n WHERE Carrier = '$carrier'\n   AND $timeFilter \n GROUP BY t ORDER BY t ",
     "rawQuery": "SELECT (intDiv(toUInt32(toDateTime(FlightDate)), 21600) * 21600) * 1000 as t, sum(ArrDel15)/count(*)*100.0 as \"Carrier Average\"\n  FROM default.ontime \n WHERE Carrier = '9E'\n   AND FlightDate >= toDate(1555911938) AND FlightDate <= toDate(1582094738) AND toDateTime(FlightDate) >= toDateTime(1555911938) AND toDateTime(FlightDate) <= toDateTime(1582094738) \n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ontime"
    },
    {
     "database": "default",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, sum(ArrDel15)/count(*)*100.0 as \"Industry Average\" \n  FROM $table \n WHERE $timeFilter \n GROUP BY t ORDER BY t ",
     "rawQuery": "SELECT (intDiv(toUInt32(toDateTime(FlightDate)), 21600) * 21600) * 1000 as t, sum(ArrDel15)/count(*)*100.0 as \"Industry Average\" \n  FROM default.ontime \n WHERE FlightDate >= toDate(1555911938) AND FlightDate <= toDate(1582094738) AND toDateTime(FlightDate) >= toDateTime(1555911938) AND toDateTime(FlightDate) <= toDateTime(1582094738) \n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Percentage of Cancelled Flights",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, sum(Cancelled)/count(*)*100.0 as \"Carrier Average\"\n  FROM $table \n WHERE Carrier = '$carrier'\n   AND $timeFilter \n GROUP BY t ORDER BY t ",
     "rawQuery": "SELECT (intDiv(toUInt32(toDateTime(FlightDate)), 21600) * 21600) * 1000 as t, sum(Cancelled)/count(*)*100.0 as \"Carrier Average\"\n  FROM default.ontime \n WHERE Carrier = '9E'\n   AND FlightDate >= toDate(1555911982) AND FlightDate <= toDate(1582094782) AND toDateTime(FlightDate) >= toDateTime(1555911982) AND toDateTime(FlightDate) <= toDateTime(1582094782) \n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ontime"
    },
    {
     "database": "default",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, sum(Cancelled)/count(*)*100.0 as \"Industry Average\" \n  FROM $table \n WHERE $timeFilter \n GROUP BY t ORDER BY t ",
     "rawQuery": "SELECT (intDiv(toUInt32(toDateTime(FlightDate)), 21600) * 21600) * 1000 as t, sum(Cancelled)/count(*)*100.0 as \"Industry Average\" \n  FROM default.ontime \n WHERE FlightDate >= toDate(1555911982) AND FlightDate <= toDate(1582094782) AND toDateTime(FlightDate) >= toDateTime(1555911982) AND toDateTime(FlightDate) <= toDateTime(1582094782) \n GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ontime"
    }
   ]
  }
 ]
}