apiVersion: 1

datasources:
  - name: clickhouse-x-auth-http
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: false
    editable: true
    jsonData:
      addCorsHeader: true
      serverName: "clickhouse"
      usePOST: true
      useYandexCloudAuthorization: true
      xHeaderUser: "demo"
      # @todo remove workaround after merge https://github.com/grafana/grafana/pull/80858
      dataSourceUrl: "http://clickhouse:8123"
      httpHeaderName1: "test-header"
    secureJsonData:
      xHeaderKey: "demo"
      httpHeaderValue1: "test-value"
