apiVersion: 1

datasources:
  - name: gh-api
    type: vertamedia-clickhouse-datasource
    editable: true
    uid: gh-api
    access: proxy
    url: https://gh-api.clickhouse.tech
    basicAuth: true
    basicAuthUser: play
    jsonData:
      addCorsHeader: false
      defaultDatabase:
      usePOST: true
      useYandexCloudAuthorization: false
      xHeaderKey:
      xHeaderUser: play
      useCompression: true
      compressionType: gzip
