apiVersion: 1

datasources:
  - name: gh-play
    type: vertamedia-clickhouse-datasource
    editable: true
    uid: gh-play
    access: proxy
    url: https://play.clickhouse.com
    basicAuth: true
    basicAuthUser: play
    jsonData:
      addCorsHeader: false
      defaultDatabase:
      usePOST: true
      useYandexCloudAuthorization: false
      xHeaderKey:
      xHeaderUser: play
      useCompression: true
      compressionType: gzip
