apiVersion: 1

datasources:
  - name: grafanalabs-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      user: default
      server: clickhouse
      port: 9000
      validate: true
    editable: true
