apiVersion: 1

datasources:
 - name: trickster
   type: vertamedia-clickhouse-datasource
   access: proxy
   url: http://trickster:8480/click1/
   editable: true
   jsonData:
     # @TODO change to true, trickster doesn't cache results with CORS header, https://github.com/tricksterproxy/trickster/issues/486
     addCorsHeader: false
     # @TODO change to true,  trickster doesn't pass SQL query via POST request body, https://github.com/tricksterproxy/trickster/issues/486
     usePOST: false
