name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Setup Go 1.19 for GopherJS
        run: |
          # Download and install Go 1.19 for GopherJS in a separate location
          wget -q https://go.dev/dl/go1.19.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz
          sudo mv /usr/local/go /usr/local/go1.19
          rm go1.19.linux-amd64.tar.gz
          
      - name: Install GopherJS
        run: |
          # Use Go 1.19 to install GopherJS
          /usr/local/go1.19/bin/go install github.com/gopherjs/gopherjs@v1.19.0-beta1
          # Make gopherjs available in PATH
          sudo ln -sf $HOME/go/bin/gopherjs /usr/local/bin/gopherjs
      - name: Install dependencies
        run: npm ci
      - name: Build plugin
        run: npm run build
      - name: Compatibility check
        run: npx @grafana/levitate@latest is-compatible --path src/module.ts --target @grafana/data,@grafana/ui,@grafana/runtime
